version: 2
jobs:
  setup_dependencies:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.lock" }}
      - run:
          command: |
            pip install --user -r requirements.lock
      - save_cache:
          key: deps-{{ checksum "requirements.lock" }}
          paths:
            - ~/.local

  test:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.lock" }}
      - run:
          name: Run tests if .py files changed
          command: |
            git fetch origin main --depth=2
            CHANGED=$(git diff --name-only origin/main...HEAD)
            echo "Changed files:"
            echo "$CHANGED"
            if echo "$CHANGED" | grep -q '\.py$'; then
              echo "Python files changed. Running tests."
              python3 -m unittest -v
            else
              echo "No Python file changes. Skipping tests."
            fi

workflows:
  version: 2
  all:
    jobs:
      - setup_dependencies
      - test:
          requires:
            - setup_dependencies
